import { Team, TeamMember } from "@/types/team"

export const TeamData: Team[] = [
  {
    id: 1,
    name: "Dr. Sovan Sankalp",
    role: "Partner & AI and Geospatial Applications Specialist",
    bio: "Leads AI-driven GIS and advanced hydrological intelligence.",
    image: "/images/team/Dr. Sovan Sankalp.jpeg",
  },
  {
    id: 2,
    name: "Dr. Asit Kumar Dandapat",
    role: "Partner & Hydrology and GIS Specialist",
    bio: "Expert in GIS-based hydrology and climate impact modelling.",
    image: "/images/team/Dr. Asit Kumar Dandapat.jpeg",
  },
  {
    id: 3,
    name: "Dr. Arpan Pradhan",
    role: "Partner & Fluvial Hydraulics Specialist",
    bio: "Specialist in river hydraulics and flood modelling systems.",
    image: "/images/team/Dr. Arpan Pradhan.jpeg",
  },
  {
    id: 4,
    name: "Aloka Prasad Mishra",
    role: "Legal, HR and Compliance Advisor",
    bio: "Handles legal compliance, labor relations, and governance.",
    image: "/images/team/Aloka Prasad Mishra.jpg",
  },
  {
    id: 5,
    name: "Chiranjeeb Kumar Sahoo",
    role: "Full-Stack Software Engineer",
    bio: "Works on IoT systems and full-stack software development.",
    image: "/images/team/Chiranjeeb Kumar Sahoo.jpeg",
  },
  {
    id: 6,
    name: "Er. A RAMAKRUSHNA SARAB",
    role: "Agricultural Engineer",
    bio: "Expertise in Remote Sensing, GIS, and agricultural systems.",
    image: "/images/team/Er. A RAMAKRUSHNA SARAB.jpeg",
  },
  {
    id: 7,
    name: "Er. Neha Choudhari",
    role: "Structural Engineer",
    bio: "Specialist in Design of RC and Steel Structures",
    image: "/images/team/Er. Neha Choudhari.jpeg",
  },
  {
    id: 8,
    name: "Er. Siddhant Mishra",
    role: "Data and AI Engineer",
    bio: "Specialist in implementing AI and Data Solutions",
    image: "/images/team/Er. Siddhant Mishra.jpeg",
  },
  {
    id: 9,
    name: "Er. Sarita Kumari Pattanaik",
    role: "Business Intelligence & Analytics Advisor",
    bio: "Specialist in BI analytics and data-driven solutions",
    image: "/images/team/Er. Sarita Kumari Pattanaik.jpeg",
  },
  {
    id: 10,
    name: "Er. Aurosish Mohanty",
    role: "Structural Design Engineer",
    bio: "Specialist in structural design and project execution",
    image: "/images/team/Er. Aurosish Mohanty.jpeg",
  },
  {
    id: 11,
    name: "Nikhil Patra",
    role: "Senior AI Engineer",
    bio: "Senior AI Engineer at SAP specializing in Document AI, data engineering, cloud-based machine learning solutions, and AI-driven application development.",
    image: "/images/team/Nikhil Patra.jpg",
  }
];

export const Team_Member: TeamMember[] = [
  {
    id: 1,
    name: "Dr. Sovan Sankalp",
    role: "Water Resources Engineer",
    domain: "Hydrology, GIS & AI/ML",
    image: "/images/team/Dr. Sovan Sankalp.jpeg",
    summary:
      "Experienced water resources engineer, researcher, and academic specializing in hydrological analysis, groundwater systems, urban flood modelling, and geospatial intelligence, with strong integration of GIS, remote sensing, and AI/ML techniques.",
    expertise: [
      "Hydrological Analysis & Modelling",
      "Groundwater Hydrology & Assessment",
      "Urban Flood Analysis & Risk Mapping",
      "Remote Sensing & GIS Applications",
      "AI/ML-based Time Series Forecasting",
      "Spatial & Temporal Drought Monitoring",
      "Urban Climate & Impervious Surface Analysis",
    ],
    experience: [
      "10+ years of research, teaching, and project experience in Water Resources Engineering",
      "Urban flood susceptibility mapping and MCDM-based risk analysis",
      "Groundwater variability and hydro-climatic extreme assessment",
      "Government- and policy-oriented research on climate resilience and sustainability",
      "Organizer and resource person for international conferences, FDPs, GIS Day events, and workshops",
    ],
    Achievements: [
      "20+ SCI/Scopus/ESCI indexed journal publications",
      "Published book chapters with Elsevier on AI/ML applications in hydrology and climate analysis",
      "Developed deep learning–based drought, soil moisture, and groundwater forecasting frameworks",
      "Reviewer for SCI & Scopus indexed journals",
      "Published three patents in geospatial intelligence, agriculture ICT, and thermal regulation systems",
    ],
    softwareSkills: [
      "HEC-RAS",
      "HEC-HMS",
      "CCHE-2D",
      "CES",
      "ArcGIS Pro",
      "ENVI",
      "ERDAS IMAGINE",
      "Google Earth Engine",
      "Python (Jupyter Notebook)",
      "R",
      "MATLAB",
      "SPSS",
      "AutoCAD",
    ],
    education: [
      "Ph.D. – Civil Engineering (Water Resources Engineering), NIT Rourkela",
      "M.Tech – Civil Engineering (Water Resources Engineering), NIT Rourkela",
      "B.Tech – Civil Engineering, SOA University, Odisha",
    ],
    ContactNumber: new Int16Array([9, 1, 7, 0, 0, 8, 0, 3, 8, 8, 3, 3]),
    email: "sankalpsovan9@gmail.com",
  },
  {
    id: 2,
    name: "Asit Kumar Dandapat",
    role: "Research Scientist",
    domain: "Hydrology & Civil Engineering",
    image: "/images/team/Dr. Asit Kumar Dandapat.jpeg",
    summary:
      "Research Scientist with 3+ years of experience in hydrology, groundwater modelling, GIS–RS, and climate impact assessment, with strong contributions to drought and flood modelling, soil erosion analysis, and sustainable water management studies.",
    expertise: [
      "Hydrology & Groundwater Modelling",
      "GIS & Remote Sensing Applications",
      "Drought & Flood Susceptibility Analysis",
      "Soil Erosion & RUSLE Modelling",
      "Climate Change Impact Assessment",
      "MCDA-based Decision Support Systems",
    ],
    experience: [
      "Research Scientist at ICAR-IIWM, working on GIS-based hydrology, groundwater modelling, and climate-resilient agriculture studies",
      "Field investigations and decision-support map generation for drought and flood assessments",
      "Civil Engineer involved in site execution, quality control, and supervision of infrastructure projects",
      "Assistant Professor teaching Civil Engineering subjects and guiding academic projects",
      "Watershed development and natural resource management under government programmes",
    ],
    Achievements: [
      "10+ SCI/Scopus indexed research publications",
      "GATE qualified in 2019, 2021, 2023, 2024, and 2025",
      "Best Poster Award – ESRI Conference 2025",
      "Best Poster Award – ICAR-IIWM Climate-Smart Agriculture 2024",
      "Recognized for GIS-based climate-smart agriculture and SDG-focused modelling studies",
    ],
    softwareSkills: [
      "ArcGIS Pro",
      "QGIS",
      "Google Earth Engine",
      "R Studio",
      "Python",
      "MODFLOW (GMS/WMS)",
      "ERDAS Imagine",
      "SNAP",
      "OriginPro",
      "MS Office",
    ],
    education: [
      "Ph.D. – Civil Engineering (Water Resources), CUTM (2021–2025)",
      "M.Tech – Water Resources Engineering, NIT Rourkela (87.30%)",
      "B.Tech – Civil Engineering, BPUT",
    ],
    ContactNumber: new Int16Array([9, 1, 8, 6, 5, 8, 0, 0, 3, 7, 1, 7]),
    email: "asit80t@gmail.com",
  },
  {
    id: 3,
    name: "Dr. Arpan Pradhan",
    role: "Water Resources Engineer",
    domain: "Fluvial Hydraulics & River Engineering",
    image: "/images/team/Dr. Arpan Pradhan.jpeg",
    summary:
      "Experienced civil engineer and academic specializing in fluvial hydraulics, river engineering, and urban flood management, integrating experimental studies, numerical modelling, and geospatial analysis for sustainable water resources solutions.",
    expertise: [
      "Fluvial & Open Channel Hydraulics",
      "River Modelling & Stream Gauging",
      "Urban Flooding & Drainage Analysis",
      "Experimental & Numerical Hydraulics",
      "Remote Sensing & GIS Applications",
      "Sustainable Water Resources Engineering",
    ],
    experience: [
      "10+ years of research and teaching experience in Water Resources Engineering",
      "PhD research on stage–discharge modelling of meandering compound channels",
      "Field expertise in river hydraulics and stream gauging trained by IAHR–WMO–IAHS (France)",
      "Contributor to government- and industry-oriented research on flood risk and hydraulic sustainability",
      "Organizer and resource person for FDPs, conferences, and national workshops",
    ],
    Achievements: [
      "15+ SCI/Scopus indexed journal publications",
      "Design Patent granted (2024) for Manual Washing Machine",
      "Patent on disease vulnerability and combat mapping using geospatial techniques",
      "Patent on sustainable bricks using iron-ore tailings and waste foundry sand",
      "Active professional memberships in ASCE, IAHR, IAHS, IEI, and ISRS",
    ],
    softwareSkills: [
      "HEC-RAS",
      "MIKE FLOOD",
      "MIKE BASIN",
      "ANSYS Fluent",
      "OpenFOAM",
      "ArcGIS",
      "QGIS",
      "MATLAB",
      "SPSS",
      "GeneXPro",
      "AutoCAD",
      "LaTeX",
    ],
    education: [
      "Ph.D. – Civil Engineering, National Institute of Technology Rourkela",
      "M.Tech – Water Resources Engineering, National Institute of Technology Rourkela",
      "B.Tech – Civil Engineering, Biju Patnaik University of Technology, Odisha",
    ],
    ContactNumber: new Int16Array([9, 1, 9, 4, 3, 9, 2, 9, 1, 9, 0, 0]),
    email: "arpan.pradhan@christuniversity.in",
  },
  {
    id: 4,
    name: "Aloka Prasad Mishra",
    role: "Law Professional Advisor",
    domain: "Legal Affairs, HR & Institutional Governance",
    image: "/images/team/Aloka Prasad Mishra.jpg",
    summary:
      "Qualified law professional with strong academic grounding in law and management, specializing in labor and industrial relations, institutional compliance, HR governance, and industry–academia coordination, supporting ethical decision-making and organizational effectiveness.",
    expertise: [
      "Labor Laws & Industrial Relations",
      "Employment Compliance & Advisory",
      "Legal Documentation & Case Interpretation",
      "Dispute Resolution & Advisory Support",
      "Institutional Governance & Compliance",
      "Industry–Academia Coordination",
    ],
    experience: [
      "Advisory support in labor and industrial relations matters",
      "Institutional compliance and governance support",
      "Training, mentoring, and academic administration roles",
      "Stakeholder coordination between academia and industry",
      "Legal documentation, regulatory reporting, and policy support",
    ],
    Achievements: [
      "Recognized for ethical decision-making and governance-oriented advisory",
      "Active contributor to institutional compliance and HR policy frameworks",
      "Mentoring-driven leadership in academic and administrative environments",
    ],
    softwareSkills: [
      "MS Office",
      "Documentation & Compliance Systems",
      "HR Information Systems (HRIS)",
      "Legal Research & Case Management Tools",
    ],
    education: [
      "Bachelor of Laws (LLB) – Labor & Industrial Relations, Madhusudan Law University",
      "MBA – HR & Finance",
    ],
    ContactNumber: new Int16Array([]),
    email: "",
  },
  {
    id: 5,
    name: "Chiranjeeb Kumar Sahoo",
    role: "Full-Stack Software Engineer",
    domain: "IoT Systems, Data & Business Analytics",
    image: "/images/team/Chiranjeeb Kumar Sahoo.jpeg",
    summary:
      "Product-driven full-stack software engineer with hands-on experience in MERN stack development, IoT system integration, and data-driven analytics. Proven ability to design and deliver scalable, real-world solutions through freelance projects, industry internships, and leadership roles within the Google Developer Groups ecosystem, combining strong engineering execution with analytical and business-oriented thinking.",
    expertise: [
      "Full-Stack Web Development (MERN Stack)",
      "Mobile Application Development (React Native)",
      "IoT Systems & Device-to-Cloud Integration",
      "RESTful API Design & Backend Services",
      "Data Analytics & Visualization",
      "Business & KPI Analytics",
      "Database Design & Optimization",
      "Scalable System Architecture",
      "Technical Leadership & Mentorship",
    ],
    experience: [
      "1.5+ years of professional experience as a Freelance Full-Stack Software Developer",
      "Designed and delivered end-to-end web and mobile applications using MERN stack and React Native",
      "6+ months of industry internship experience contributing to live production systems",
      "Hands-on exposure to software development lifecycles, debugging, and collaborative engineering workflows",
      "GDG Sub-Lead (2024) and GDG Lead (2025), leading developer communities and technical initiatives",
    ],
    Achievements: [
      "Winner of 5+ national-level hackathons",
      "Recognized for innovation, rapid prototyping, and problem-solving capabilities",
      "Leadership roles as Google Developer Groups (GDG) Sub-Lead (2024) and Lead (2025)",
      "Successful delivery of multiple freelance and real-world software projects",
    ],
    softwareSkills: [
      "JavaScript",
      "Python",
      "React",
      "React Native",
      "Node.js",
      "Express.js",
      "MongoDB",
      "FastAPI",
      "REST APIs",
      "Git",
      "GitHub",
      "Pandas (Exposure)",
      "NumPy (Exposure)",
      "Data Visualization Tools",
      "Cloud & CI/CD Tools (Exposure)",
    ],
    education: [
      "B.Tech – Computer Science & Engineering, Gandhi Institute for Education and Technology (GIET), Bhubaneswar (2023–2027)",
    ],
    ContactNumber: new Int16Array([9, 1, 6, 3, 7, 1, 8, 5, 0, 0, 0, 5]),
    email: "chiranjeeb.dev@gmail.com",
  },
  {
    id: 6,
    name: "Er. A Ramakrushna Sarab",
    role: "Agricultural Engineer",
    domain: "Remote Sensing, GIS & Agricultural Systems",
    image: "/images/team/Er. A RAMAKRUSHNA SARAB.jpeg",
    summary:
      "Agricultural engineer with interdisciplinary expertise in Remote Sensing and GIS applied to agricultural and water resource systems. Actively involved in geospatial analysis for crop monitoring, watershed management, and climate variability studies, with strong capability in integrating satellite-derived data with field observations to support precision agriculture, sustainable resource planning, and evidence-based agricultural management.",
    expertise: [
      "Hydrological Trend Analysis & Modelling",
      "Sustainable Water & Agricultural Management",
      "Geospatial Technology (Remote Sensing & GIS)",
      "Watershed Management",
      "Evaluation of Soil & Water Conservation Structures",
      "Natural Resource Management",
      "Precision Agriculture Applications",
    ],
    experience: [
      "GIS expert for REWARD–Hydrology Project funded by DSC-WD and the World Bank",
      "Technical contributor in evaluation of a major irrigation project funded by CWC Consultancy",
      "Hands-on experience in geospatial analysis for land and water resource management",
    ],
    Achievements: [
      "Applied geospatial technologies to large-scale hydrology and irrigation projects",
      "Contributed to data-driven decision-making for sustainable water resource planning",
      "Field-integrated GIS analysis supporting agricultural and environmental studies",
    ],
    softwareSkills: [
      "QGIS (Quantum GIS)",
      "ArcMap",
      "ArcGIS Pro",
      "Google Earth Pro",
      "C Programming",
      "AutoCAD",
      "R Studio",
      "MODFLOW-NWT",
      "ModelMuse",
    ],
    education: [
      "B.Tech – Agricultural Engineering, College of Agricultural Engineering & Technology (CAET), OUAT, Odisha",
    ],
    ContactNumber: new Int16Array([7, 8, 7, 3, 8, 4, 5, 8, 5, 8]),
    email: "aramakrushna.00@gmail.com",
  },
  {
    id: 8,
    name: "Siddhant Mishra",
    role: "Applied AI & Machine Learning Engineer",
    domain: "Machine Learning, Data Engineering & Decision Support Systems",
    image: "/images/team/Er. Siddhant Mishra.jpeg",
    summary:
      "Applied Machine Learning professional with hands-on experience in building, training, and integrating data-driven models into real-world research and enterprise systems. Strong background in machine learning, statistical analysis, and data engineering, with practical exposure to ensemble methods, deep learning architectures, and end-to-end ML pipelines for decision support, fraud detection, and language- and vision-based applications.",
    expertise: [
      "Applied Machine Learning & Statistical Modelling",
      "End-to-End ML Pipelines & Model Deployment",
      "Decision Support Systems",
      "Fraud Detection & Risk Analytics",
      "Data Engineering & ETL Frameworks",
      "Ensemble Learning (XGBoost, LightGBM, CatBoost)",
      "Deep Learning (CNNs, Autoencoders)",
      "Language & Vision-Based AI Systems",
    ],
    experience: [
      "Project Associate at AHRC, IIT Bhubaneswar contributing to irrigation decision support systems using data-driven modelling",
      "Developed and trained machine learning models for agricultural and water resource planning applications",
      "Worked on Odia Handwritten Text Recognition (HTR) pipelines including dataset preparation and model experimentation",
      "Designed and maintained research frameworks integrating FastAPI (Python) and Next.js",
      "Analyst / Data Engineer at Accenture designing cloud-based data warehousing solutions using Azure Databricks and Snowflake",
      "Built metadata-driven ETL frameworks and implemented fraud detection models for insurance analytics",
      "Associate Software Engineer / Data Analyst at MITS focusing on predictive analytics, SQL-based data modelling, and dashboards",
    ],
    Achievements: [
      "Pinnacle Award recipient at Accenture for performance excellence",
      "Microsoft Certified – Azure Data Fundamentals (DP-900)",
      "Developed production-ready fraud detection and decision support systems",
      "Contributed to multiple research projects involving optimization algorithms and intelligent systems",
    ],
    softwareSkills: [
      "Python",
      "PySpark",
      "Pandas",
      "NumPy",
      "SQL",
      "Azure",
      "Snowflake",
      "FastAPI",
      "Next.js",
      "Git",
      "Azure DevOps",
    ],
    education: [
      "B.Tech – Odisha University of Technology and Research (Formerly CET), CGPA: 9.21",
      "Post Graduate Diploma – Applied Statistics",
    ],
    ContactNumber: new Int16Array([9, 1, 8, 0, 5, 8, 0, 6, 7, 4, 7, 3]),
    email: "siddhant mishra23@outlook.com",
  },
  {
    id: 9,
    name: "Sarita Kumari Pattanaik",
    role: "Business Intelligence & Analytics Advisor",
    domain: "Business Intelligence, Data Analytics & Reporting",
    image: "/images/team/Er. Sarita Kumari Pattanaik.jpeg",
    summary:
      "Experienced IT professional with 13+ years of experience working with leading MNCs, delivering data-driven solutions across retail, manufacturing, and finance domains. Proven expertise in BI analytics, reporting, and data visualization, supporting business decision-making through scalable analytics solutions. Hands-on experience working with global clients and cross-functional teams across international markets.",
    expertise: [
      "Business Intelligence & Analytics Solutions",
      "Data Reporting & Dashboard Development",
      "Retail, Manufacturing & Finance Analytics",
      "Enterprise Data Analysis & Insights Generation",
      "Client Delivery & Stakeholder Collaboration",
      "Data Visualization & BI Tools",
      "Cross-functional Team Collaboration",
    ],
    experience: [
      "13+ years of IT experience with leading MNCs",
      "Delivered analytics solutions for retail customers across Singapore and the USA",
      "Worked with global clients across international markets",
      "Developed and maintained BI reporting solutions for retail, manufacturing, and finance domains",
      "Collaborated with cross-functional teams to support business decision-making",
    ],
    Achievements: [
      "Microsoft Certified Power BI Professional",
      "Successfully delivered analytics solutions for retail customers across Singapore and the USA",
      "13+ years of consistent delivery in data-driven solutions",
    ],
    softwareSkills: [
      "Power BI",
      "MySQL",
      "Oracle Database",
      "Strategy One",
      "BI Reporting Tools",
    ],
    education: [
      "Engineering Graduate (Er. prefix)",
    ],
    ContactNumber: new Int16Array([]),
    email: "",
  },
  {
    id: 10,
    name: "Aurosish Mohanty",
    role: "Structural Design Engineer",
    domain: "Structural Engineering, Design & Construction",
    image: "/images/team/Er. Aurosish Mohanty.jpeg",
    summary:
      "Result-oriented Structural Engineer with over 4 years of professional experience in structural design, construction, and project execution across industrial, infrastructure, and building projects. Experienced in handling government and private sector projects, coordinating with multidisciplinary teams, and delivering optimized structural solutions. Proven expertise in proof checking, structural vetting, strengthening and retrofitting works, and handling both domestic and international clients.",
    expertise: [
      "Structural Design of RCC & Steel Structures",
      "Industrial, Commercial & Infrastructure Projects",
      "Structural Proof Checking & Vetting Coordination",
      "Retrofitting & Strengthening of Structures",
      "Water Retaining Structures (ETP, PSTP, SPS & UG Tanks)",
      "Steel Shed, Truss & Industrial Structural Design",
      "Client Coordination & Project Execution",
      "Multidisciplinary Team Coordination",
    ],
    experience: [
      "4+ years of professional experience in structural design and construction",
      "Structural design for industrial platforms, pipe supports, sheds, and plant structures",
      "Multistoried hospital and institutional building projects",
      "Design of underground tanks, drainage, and infrastructure structures",
      "Bridge components including abutments, retaining walls, and protection works",
      "Design and detailing of industrial and infrastructure facilities across multiple sectors",
      "Handled government and private sector projects",
      "Coordinated with domestic and international clients",
    ],
    Achievements: [
      "Successfully delivered structural solutions across industrial, infrastructure, and building projects",
      "Expertise in handling complex retrofitting and strengthening projects",
      "Proven track record in multidisciplinary team coordination and project execution",
    ],
    softwareSkills: [
      "STAAD Pro",
      "ETABS",
      "SAFE",
      "SAP2000",
      "STRAP",
      "AutoCAD",
      "DraftSight",
      "MS Excel",
      "MS PowerPoint",
    ],
    education: [
      "B.Tech in Civil Engineering (Er. prefix)",
    ],
    ContactNumber: new Int16Array([]),
    email: "",
  },
  {
    id: 11,
    name: "Nikhil Patra",
    role: "Senior AI Engineer",
    domain: "Artificial Intelligence, Data Engineering & Cloud Solutions",
    image: "/images/team/Nikhil Patra.jpeg",
    summary:
      "Senior AI Engineer at SAP with extensive experience in Document AI and Data Engineering within SAP’s AI organization. Spearheading data initiatives and leading engineering teams to build scalable data pipelines, knowledge graphs, and cloud-based machine learning solutions. Experienced in AI-driven document processing, Retrieval-Augmented Generation (RAG), data lakes, and automation using AWS and SAP BTP. Strong background in full-stack development, research, and agile project management with expertise in delivering enterprise-grade AI solutions.",
    expertise: [
      "Document AI & Machine Learning Solutions",
      "Data Engineering & Automated Data Pipelines",
      "Knowledge Graphs & RAG Implementation",
      "Cloud Platforms (AWS, SAP BTP, AI Core)",
      "Full Stack Application Development",
      "Agile Methodologies, Scrum & TDD",
      "Project & Vendor Management",
      "Semantic Web & Data-Centric Systems",
    ],
    experience: [
      "11+ years of experience at SAP across AI development, data engineering, and software engineering roles",
      "Design and implementation of cloud-based ML document processing solutions",
      "Leadership of Data Engineering team managing annotation and data acquisition projects",
      "Development of knowledge graphs integrating heterogeneous data sources",
      "Experience in microservices-based payroll applications on HANA Cloud Platform",
      "Research experience in cyber defense, semantic data quality, and image processing",
      "Enterprise application development in HCM Recruiting and Payroll systems",
      "Experience working with banking, healthcare, and enterprise AI domains",
    ],
    Achievements: [
      "Led key AI data initiatives within SAP’s AI organization",
      "Built scalable data lakes and automated high-quality training data pipelines",
      "Successfully delivered AI-powered cloud solutions for enterprise applications",
      "Experience as Mindfulness Ambassador and Search Inside Yourself Trainer at SAP",
    ],
    softwareSkills: [
      "Python",
      "Java",
      "JavaScript",
      "C++",
      "AWS",
      "SAP BTP",
      "AI Core",
      "Metaflow",
      "UI5",
      "HANA Cloud Platform",
    ],
    education: [
      "M.Sc. in Computer Science – University of Bonn",
      "B.Tech in Computer Science and Engineering – Vellore Institute of Technology",
    ],
    ContactNumber: new Int16Array([]),
    email: "",
  }
];
