import { Team, TeamMember } from "@/types/team"

export const TeamData: Team[] = [
  {
    id: 1,
    name: "Dr. Sovan Sankalp",
    role: "Partner & AI and Geospatial Applications Specialist",
    bio: "Leads AI-driven GIS and advanced hydrological intelligence.",
    image: "/images/team/Dr. Sovan Sankalp.jpeg",
  },
  {
    id: 2,
    name: "Dr. Asit Kumar Dandapat",
    role: "Partner & Hydrology and GIS Specialist",
    bio: "Expert in GIS-based hydrology and climate impact modelling.",
    image: "/images/team/Dr. Asit Kumar Dandapat.jpeg",
  },
  {
    id: 3,
    name: "Dr. Arpan Pradhan",
    role: "Partner & Fluvial Hydraulics Specialist",
    bio: "Specialist in river hydraulics and flood modelling systems.",
    image: "/images/team/Dr. Arpan Pradhan.jpeg",
  },
  {
    id: 4,
    name: "Aloka Prasad Mishra",
    role: "Legal, HR and Compliance Advisor",
    bio: "Handles legal compliance, labor relations, and governance.",
    image: "/images/team/Aloka Prasad Mishra.jpg",
  },
  {
    id: 5,
    name: "Chiranjeeb Kumar Sahoo",
    role: "Full-Stack Software Engineer",
    bio: "Works on IoT systems and full-stack software development.",
    image: "/images/team/Chiranjeeb Kumar Sahoo.jpeg",
  },
  {
    id: 6,
    name: "Er. A RAMAKRUSHNA SARAB",
    role: "Agricultural Engineer",
    bio: "Expertise in Remote Sensing, GIS, and agricultural systems.",
    image: "/images/team/Er. A RAMAKRUSHNA SARAB.jpeg",
  },
  {
    id: 7,
    name: "Er. Neha Choudhari",
    role: "Structural Engineer",
    bio: "Specialist in Design of RC and Steel Structures",
    image: "/images/team/Er. Neha Choudhari.jpeg",
  },
  {
    id: 8,
    name: "Er. Siddhant Mishra",
    role: "Data and AI Engineer",
    bio: "Specialist in implementing AI and Data Solutions",
    image: "/images/team/Er. Siddhant Mishra.jpeg",
  },
  {
    id: 9,
    name: "Er. Sarita Kumari Pattanaik",
    role: "Business Intelligence & Analytics Advisor",
    bio: "Specialist in BI analytics and data-driven solutions",
    image: "/images/team/Er. Sarita Kumari Pattanaik.jpeg",
  },
  {
    id: 10,
    name: "Er. Aurosish Mohanty",
    role: "Structural Design Engineer",
    bio: "Specialist in structural design and project execution",
    image: "/images/team/Er. Aurosish Mohanty.jpeg",
  },
  {
    id: 11,
    name: "Nikhil Patra",
    role: "Senior AI Engineer",
    bio: "Senior AI Engineer at SAP specializing in Document AI, data engineering, cloud-based machine learning solutions, and AI-driven application development.",
    image: "/images/team/Nikhil Patra.jpg",
  },
  {
    id: 12,
    name: "Dr. Aniket Bhalkikar",
    role: "Structural Engineering & Seismic Safety Specialist",
    bio: "Specialist in structural safety, seismic hazard assessment, and health monitoring.",
    image: "/images/team/Aniket Bhalkikar.jpg",
  },
  {
    id: 13,
    name: "Er. Abhishek Samanta",
    role: "Civil Engineering & Infrastructure Solutions Contractor",
    bio: "PWD registered contractor with extensive experience in executing government infrastructure, roads, and bridges.",
    image: "/images/team/Abhishek Samanta.jpg",
  },
  {
    id: 14,
    name: "Er. Sumit Pattanayak",
    role: "Associated Contractor – Civil & Infrastructure",
    bio: "Class ‘A’ PWD Contractor with a decade of expertise executing high-value healthcare, academic, and commercial infrastructure.",
    image: "/images/team/Sumit Pattanayak.jpg",
  },
  {
    id: 15,
    name: "Dr. Ketan Kumar Nandi",
    role: "Fluvial Hydrodynamics & River Modeler Consultant",
    bio: "Specialist in river hydrodynamics, morphological assessment of braided rivers, and remote sensing applications.",
    image: "/images/team/Ketan Kumar Nandi.jpg",
  },
  {
    id: 16,
    name: "Dr. Anindita Nath",
    role: "Remote Sensing & Geospatial Analyst Consultant",
    bio: "Specialist in remote sensing, GIS, coastal hazards, and land-use monitoring.",
    image: "/images/team/Anindita Nath.jpg",
  },
  {
    id: 17,
    name: "Dr. M. Uma Maheswar Rao",
    role: "GIS Analyst, SCRUM Master & Water Resources Specialist",
    bio: "Specialist in urban planning, hydrology, and digital twin modeling using remote sensing, GIS, and agile workflows.",
    image: "/images/team/M Uma Maheswar Rao.jpg",
  }
];

export const Team_Member: TeamMember[] = [
  {
    id: 1,
    name: "Dr. Sovan Sankalp",
    role: "Water Resources Engineer",
    domain: "Hydrology, GIS & AI/ML",
    image: "/images/team/Dr. Sovan Sankalp.jpeg",
    summary:
      "Experienced water resources engineer, researcher, and academic specializing in hydrological analysis, groundwater systems, urban flood modelling, and geospatial intelligence, with strong integration of GIS, remote sensing, and AI/ML techniques.",
    expertise: [
      "Hydrological Analysis & Modelling",
      "Groundwater Hydrology & Assessment",
      "Urban Flood Analysis & Risk Mapping",
      "Remote Sensing & GIS Applications",
      "AI/ML-based Time Series Forecasting",
      "Spatial & Temporal Drought Monitoring",
      "Urban Climate & Impervious Surface Analysis",
    ],
    experience: [
      "10+ years of research, teaching, and project experience in Water Resources Engineering",
      "Urban flood susceptibility mapping and MCDM-based risk analysis",
      "Groundwater variability and hydro-climatic extreme assessment",
      "Government- and policy-oriented research on climate resilience and sustainability",
      "Organizer and resource person for international conferences, FDPs, GIS Day events, and workshops",
    ],
    Achievements: [
      "20+ SCI/Scopus/ESCI indexed journal publications",
      "Published book chapters with Elsevier on AI/ML applications in hydrology and climate analysis",
      "Developed deep learning–based drought, soil moisture, and groundwater forecasting frameworks",
      "Reviewer for SCI & Scopus indexed journals",
      "Published three patents in geospatial intelligence, agriculture ICT, and thermal regulation systems",
    ],
    softwareSkills: [
      "HEC-RAS",
      "HEC-HMS",
      "CCHE-2D",
      "CES",
      "ArcGIS Pro",
      "ENVI",
      "ERDAS IMAGINE",
      "Google Earth Engine",
      "Python (Jupyter Notebook)",
      "R",
      "MATLAB",
      "SPSS",
      "AutoCAD",
    ],
    education: [
      "Ph.D. – Civil Engineering (Water Resources Engineering), NIT Rourkela",
      "M.Tech – Civil Engineering (Water Resources Engineering), NIT Rourkela",
      "B.Tech – Civil Engineering, SOA University, Odisha",
    ],
    ContactNumber: "+91-7008038833",
    email: "sankalpsovan9@gmail.com",
  },
  {
    id: 2,
    name: "Dr. Asit Kumar Dandapat",
    role: "Research Scientist",
    domain: "Hydrology & Civil Engineering",
    image: "/images/team/Dr. Asit Kumar Dandapat.jpeg",
    summary:
      "Research Scientist with 3+ years of experience in hydrology, groundwater modelling, GIS–RS, and climate impact assessment, with strong contributions to drought and flood modelling, soil erosion analysis, and sustainable water management studies.",
    expertise: [
      "Hydrology & Groundwater Modelling",
      "GIS & Remote Sensing Applications",
      "Drought & Flood Susceptibility Analysis",
      "Soil Erosion & RUSLE Modelling",
      "Climate Change Impact Assessment",
      "MCDA-based Decision Support Systems",
    ],
    experience: [
      "Research Scientist at ICAR-IIWM, working on GIS-based hydrology, groundwater modelling, and climate-resilient agriculture studies",
      "Field investigations and decision-support map generation for drought and flood assessments",
      "Civil Engineer involved in site execution, quality control, and supervision of infrastructure projects",
      "Assistant Professor teaching Civil Engineering subjects and guiding academic projects",
      "Watershed development and natural resource management under government programmes",
    ],
    Achievements: [
      "10+ SCI/Scopus indexed research publications",
      "GATE qualified in 2019, 2021, 2023, 2024, and 2025",
      "Best Poster Award – ESRI Conference 2025",
      "Best Poster Award – ICAR-IIWM Climate-Smart Agriculture 2024",
      "Recognized for GIS-based climate-smart agriculture and SDG-focused modelling studies",
    ],
    softwareSkills: [
      "ArcGIS Pro",
      "QGIS",
      "Google Earth Engine",
      "R Studio",
      "Python",
      "MODFLOW (GMS/WMS)",
      "ERDAS Imagine",
      "SNAP",
      "OriginPro",
      "MS Office",
    ],
    education: [
      "Ph.D. – Civil Engineering (Water Resources), CUTM (2021–2025)",
      "M.Tech – Water Resources Engineering, NIT Rourkela (87.30%)",
      "B.Tech – Civil Engineering, BPUT",
    ],
    ContactNumber: "+91-8658003717",
    email: "asit80t@gmail.com",
  },
  {
    id: 3,
    name: "Dr. Arpan Pradhan",
    role: "Water Resources Engineer",
    domain: "Fluvial Hydraulics & River Engineering",
    image: "/images/team/Dr. Arpan Pradhan.jpeg",
    summary:
      "Experienced civil engineer and academic specializing in fluvial hydraulics, river engineering, and urban flood management, integrating experimental studies, numerical modelling, and geospatial analysis for sustainable water resources solutions.",
    expertise: [
      "Fluvial & Open Channel Hydraulics",
      "River Modelling & Stream Gauging",
      "Urban Flooding & Drainage Analysis",
      "Experimental & Numerical Hydraulics",
      "Remote Sensing & GIS Applications",
      "Sustainable Water Resources Engineering",
    ],
    experience: [
      "10+ years of research and teaching experience in Water Resources Engineering",
      "PhD research on stage–discharge modelling of meandering compound channels",
      "Field expertise in river hydraulics and stream gauging trained by IAHR–WMO–IAHS (France)",
      "Contributor to government- and industry-oriented research on flood risk and hydraulic sustainability",
      "Organizer and resource person for FDPs, conferences, and national workshops",
    ],
    Achievements: [
      "15+ SCI/Scopus indexed journal publications",
      "Design Patent granted (2024) for Manual Washing Machine",
      "Patent on disease vulnerability and combat mapping using geospatial techniques",
      "Patent on sustainable bricks using iron-ore tailings and waste foundry sand",
      "Active professional memberships in ASCE, IAHR, IAHS, IEI, and ISRS",
    ],
    softwareSkills: [
      "HEC-RAS",
      "MIKE FLOOD",
      "MIKE BASIN",
      "ANSYS Fluent",
      "OpenFOAM",
      "ArcGIS",
      "QGIS",
      "MATLAB",
      "SPSS",
      "GeneXPro",
      "AutoCAD",
      "LaTeX",
    ],
    education: [
      "Ph.D. – Civil Engineering, National Institute of Technology Rourkela",
      "M.Tech – Water Resources Engineering, National Institute of Technology Rourkela",
      "B.Tech – Civil Engineering, Biju Patnaik University of Technology, Odisha",
    ],
    ContactNumber: "+91-9439291900",
    email: "arpan.pradhan@christuniversity.in",
  },
  {
    id: 4,
    name: "Aloka Prasad Mishra",
    role: "Law Professional Advisor",
    domain: "Legal Affairs, HR & Institutional Governance",
    image: "/images/team/Aloka Prasad Mishra.jpg",
    summary:
      "Qualified law professional with strong academic grounding in law and management, specializing in labor and industrial relations, institutional compliance, HR governance, and industry–academia coordination, supporting ethical decision-making and organizational effectiveness.",
    expertise: [
      "Labor Laws & Industrial Relations",
      "Employment Compliance & Advisory",
      "Legal Documentation & Case Interpretation",
      "Dispute Resolution & Advisory Support",
      "Institutional Governance & Compliance",
      "Industry–Academia Coordination",
    ],
    experience: [
      "Advisory support in labor and industrial relations matters",
      "Institutional compliance and governance support",
      "Training, mentoring, and academic administration roles",
      "Stakeholder coordination between academia and industry",
      "Legal documentation, regulatory reporting, and policy support",
    ],
    Achievements: [
      "Recognized for ethical decision-making and governance-oriented advisory",
      "Active contributor to institutional compliance and HR policy frameworks",
      "Mentoring-driven leadership in academic and administrative environments",
    ],
    softwareSkills: [
      "MS Office",
      "Documentation & Compliance Systems",
      "HR Information Systems (HRIS)",
      "Legal Research & Case Management Tools",
    ],
    education: [
      "Bachelor of Laws (LLB) – Labor & Industrial Relations, Madhusudan Law University",
      "MBA – HR & Finance",
    ],
    ContactNumber: "",
    email: "",
  },
  {
    id: 5,
    name: "Chiranjeeb Kumar Sahoo",
    role: "Full-Stack Software Engineer",
    domain: "IoT Systems, Data & Business Analytics",
    image: "/images/team/Chiranjeeb Kumar Sahoo.jpeg",
    summary:
      "Product-driven full-stack software engineer with hands-on experience in MERN stack development, IoT system integration, and data-driven analytics. Proven ability to design and deliver scalable, real-world solutions through freelance projects, industry internships, and leadership roles within the Google Developer Groups ecosystem, combining strong engineering execution with analytical and business-oriented thinking.",
    expertise: [
      "Full-Stack Web Development (MERN Stack)",
      "Mobile Application Development (React Native)",
      "IoT Systems & Device-to-Cloud Integration",
      "RESTful API Design & Backend Services",
      "Data Analytics & Visualization",
      "Business & KPI Analytics",
      "Database Design & Optimization",
      "Scalable System Architecture",
      "Technical Leadership & Mentorship",
    ],
    experience: [
      "1.5+ years of professional experience as a Freelance Full-Stack Software Developer",
      "Designed and delivered end-to-end web and mobile applications using MERN stack and React Native",
      "6+ months of industry internship experience contributing to live production systems",
      "Hands-on exposure to software development lifecycles, debugging, and collaborative engineering workflows",
      "GDG Sub-Lead (2024) and GDG Lead (2025), leading developer communities and technical initiatives",
    ],
    Achievements: [
      "Winner of 5+ national-level hackathons",
      "Recognized for innovation, rapid prototyping, and problem-solving capabilities",
      "Leadership roles as Google Developer Groups (GDG) Sub-Lead (2024) and Lead (2025)",
      "Successful delivery of multiple freelance and real-world software projects",
    ],
    softwareSkills: [
      "JavaScript",
      "Python",
      "React",
      "React Native",
      "Node.js",
      "Express.js",
      "MongoDB",
      "FastAPI",
      "REST APIs",
      "Git",
      "GitHub",
      "Pandas (Exposure)",
      "NumPy (Exposure)",
      "Data Visualization Tools",
      "Cloud & CI/CD Tools (Exposure)",
    ],
    education: [
      "B.Tech – Computer Science & Engineering, Gandhi Institute for Education and Technology (GIET), Bhubaneswar (2023–2027)",
    ],
    ContactNumber: "+91-6371850005",
    email: "chiranjeeb.dev@gmail.com",
  },
  {
    id: 6,
    name: "Er. A Ramakrushna Sarab",
    role: "Agricultural Engineer",
    domain: "Remote Sensing, GIS & Agricultural Systems",
    image: "/images/team/Er. A RAMAKRUSHNA SARAB.jpeg",
    summary:
      "Agricultural engineer with interdisciplinary expertise in Remote Sensing and GIS applied to agricultural and water resource systems. Actively involved in geospatial analysis for crop monitoring, watershed management, and climate variability studies, with strong capability in integrating satellite-derived data with field observations to support precision agriculture, sustainable resource planning, and evidence-based agricultural management.",
    expertise: [
      "Hydrological Trend Analysis & Modelling",
      "Sustainable Water & Agricultural Management",
      "Geospatial Technology (Remote Sensing & GIS)",
      "Watershed Management",
      "Evaluation of Soil & Water Conservation Structures",
      "Natural Resource Management",
      "Precision Agriculture Applications",
    ],
    experience: [
      "GIS expert for REWARD–Hydrology Project funded by DSC-WD and the World Bank",
      "Technical contributor in evaluation of a major irrigation project funded by CWC Consultancy",
      "Hands-on experience in geospatial analysis for land and water resource management",
    ],
    Achievements: [
      "Applied geospatial technologies to large-scale hydrology and irrigation projects",
      "Contributed to data-driven decision-making for sustainable water resource planning",
      "Field-integrated GIS analysis supporting agricultural and environmental studies",
    ],
    softwareSkills: [
      "QGIS (Quantum GIS)",
      "ArcMap",
      "ArcGIS Pro",
      "Google Earth Pro",
      "C Programming",
      "AutoCAD",
      "R Studio",
      "MODFLOW-NWT",
      "ModelMuse",
    ],
    education: [
      "B.Tech – Agricultural Engineering, College of Agricultural Engineering & Technology (CAET), OUAT, Odisha",
    ],
    ContactNumber: "+91-7873845858",
    email: "aramakrushna.00@gmail.com",
  },
  {
    id: 7,
    name: "Er. Neha Choudhari",
    role: "Structural Design Engineer",
    domain: "Structural Engineering & High-Rise Design",
    image: "/images/team/Er. Neha Choudhari.jpeg",
    summary:
      "Performance-focused structural design engineer with 12+ years of experience in structural analysis, design, and detailing of high-rise structures, reinforced concrete (RC), and steel structures compliant with international and Indian standards.",
    expertise: [
      "Structural Analysis & Design of RC & Steel Structures",
      "High-Rise Building Detailing (up to 36 floors)",
      "Foot over Bridge (FOB) Designing",
      "Structural Retrofitting & Repair",
      "Offshore Skids & Industrial Shed Modelling",
      "Site Quality Coordination & Inspection",
    ],
    experience: [
      "Freelancer Structural Design Engineer (2019–Present) designing multiplexes, apartments, school strengthening, and industrial sheds across Maharashtra and Telangana",
      "Structural Design Engineer at SR Consultant, Aurangabad (2021–2022) designing Foot over Bridges and R&D buildings",
      "Assistant Professor at Vidya Jyothi Institute of Technology, Hyderabad (2018)",
      "Structural Engineer at My Home Constructions Pvt. Ltd., Hyderabad (2013–2018) designing residential high-rises up to 36 floors",
      "Trainee Structural Engineer at Sumatec Inc., Aurangabad (2012–2013) analyzing offshore skids and Essar proof checking",
    ],
    Achievements: [
      "Designed and analyzed landmark residential high-rises including My Home Bhooja (36 floors), My Home Avatar (30 floors), and My Home Krishe (25 floors)",
      "Assisted in the structural design elements of the Statue of Equality project in Shamshabad, Hyderabad",
      "Completed research publication on Shear in Flexural Members under IS 456-2000 and ACI 318-08 at SV University",
      "Chartered Engineer (India) and Member of the Institution of Engineers (MIE)",
    ],
    softwareSkills: [
      "ETABS",
      "STAAD Pro",
      "SAFE",
      "AutoCAD",
      "SAP2000",
      "MATLAB",
      "MS Office",
    ],
    education: [
      "M.E. – Structural Engineering, Government College of Engineering, Aurangabad",
      "B.E. – Civil Engineering, Marathwada Institute of Technology (MIT), Aurangabad",
    ],
    ContactNumber: "+91-9985044056",
    email: "nehaac22@gmail.com",
  },
  {
    id: 8,
    name: "Siddhant Mishra",
    role: "Applied AI & Machine Learning Engineer",
    domain: "Machine Learning, Data Engineering & Decision Support Systems",
    image: "/images/team/Er. Siddhant Mishra.jpeg",
    summary:
      "Applied Machine Learning professional with hands-on experience in building, training, and integrating data-driven models into real-world research and enterprise systems. Strong background in machine learning, statistical analysis, and data engineering, with practical exposure to ensemble methods, deep learning architectures, and end-to-end ML pipelines for decision support, fraud detection, and language- and vision-based applications.",
    expertise: [
      "Applied Machine Learning & Statistical Modelling",
      "End-to-End ML Pipelines & Model Deployment",
      "Decision Support Systems",
      "Fraud Detection & Risk Analytics",
      "Data Engineering & ETL Frameworks",
      "Ensemble Learning (XGBoost, LightGBM, CatBoost)",
      "Deep Learning (CNNs, Autoencoders)",
      "Language & Vision-Based AI Systems",
    ],
    experience: [
      "Project Associate at AHRC, IIT Bhubaneswar contributing to irrigation decision support systems using data-driven modelling",
      "Developed and trained machine learning models for agricultural and water resource planning applications",
      "Worked on Odia Handwritten Text Recognition (HTR) pipelines including dataset preparation and model experimentation",
      "Designed and maintained research frameworks integrating FastAPI (Python) and Next.js",
      "Analyst / Data Engineer at Accenture designing cloud-based data warehousing solutions using Azure Databricks and Snowflake",
      "Built metadata-driven ETL frameworks and implemented fraud detection models for insurance analytics",
      "Associate Software Engineer / Data Analyst at MITS focusing on predictive analytics, SQL-based data modelling, and dashboards",
    ],
    Achievements: [
      "Pinnacle Award recipient at Accenture for performance excellence",
      "Microsoft Certified – Azure Data Fundamentals (DP-900)",
      "Developed production-ready fraud detection and decision support systems",
      "Contributed to multiple research projects involving optimization algorithms and intelligent systems",
    ],
    softwareSkills: [
      "Python",
      "PySpark",
      "Pandas",
      "NumPy",
      "SQL",
      "Azure",
      "Snowflake",
      "FastAPI",
      "Next.js",
      "Git",
      "Azure DevOps",
    ],
    education: [
      "B.Tech – Odisha University of Technology and Research (Formerly CET), CGPA: 9.21",
      "Post Graduate Diploma – Applied Statistics",
    ],
    ContactNumber: "+91-8058067473",
    email: "siddhant mishra23@outlook.com",
  },
  {
    id: 9,
    name: "Sarita Kumari Pattanaik",
    role: "Business Intelligence & Analytics Advisor",
    domain: "Business Intelligence, Data Analytics & Reporting",
    image: "/images/team/Er. Sarita Kumari Pattanaik.jpeg",
    summary:
      "Experienced IT professional with 13+ years of experience working with leading MNCs, delivering data-driven solutions across retail, manufacturing, and finance domains. Proven expertise in BI analytics, reporting, and data visualization, supporting business decision-making through scalable analytics solutions. Hands-on experience working with global clients and cross-functional teams across international markets.",
    expertise: [
      "Business Intelligence & Analytics Solutions",
      "Data Reporting & Dashboard Development",
      "Retail, Manufacturing & Finance Analytics",
      "Enterprise Data Analysis & Insights Generation",
      "Client Delivery & Stakeholder Collaboration",
      "Data Visualization & BI Tools",
      "Cross-functional Team Collaboration",
    ],
    experience: [
      "13+ years of IT experience with leading MNCs",
      "Delivered analytics solutions for retail customers across Singapore and the USA",
      "Worked with global clients across international markets",
      "Developed and maintained BI reporting solutions for retail, manufacturing, and finance domains",
      "Collaborated with cross-functional teams to support business decision-making",
    ],
    Achievements: [
      "Microsoft Certified Power BI Professional",
      "Successfully delivered analytics solutions for retail customers across Singapore and the USA",
      "13+ years of consistent delivery in data-driven solutions",
    ],
    softwareSkills: [
      "Power BI",
      "MySQL",
      "Oracle Database",
      "Strategy One",
      "BI Reporting Tools",
    ],
    education: [
      "Engineering Graduate (Er. prefix)",
    ],
    ContactNumber: "",
    email: "",
  },
  {
    id: 10,
    name: "Aurosish Mohanty",
    role: "Structural Design Engineer",
    domain: "Structural Engineering, Design & Construction",
    image: "/images/team/Er. Aurosish Mohanty.jpeg",
    summary:
      "Result-oriented Structural Engineer with over 4 years of professional experience in structural design, construction, and project execution across industrial, infrastructure, and building projects. Experienced in handling government and private sector projects, coordinating with multidisciplinary teams, and delivering optimized structural solutions. Proven expertise in proof checking, structural vetting, strengthening and retrofitting works, and handling both domestic and international clients.",
    expertise: [
      "Structural Design of RCC & Steel Structures",
      "Industrial, Commercial & Infrastructure Projects",
      "Structural Proof Checking & Vetting Coordination",
      "Retrofitting & Strengthening of Structures",
      "Water Retaining Structures (ETP, PSTP, SPS & UG Tanks)",
      "Steel Shed, Truss & Industrial Structural Design",
      "Client Coordination & Project Execution",
      "Multidisciplinary Team Coordination",
    ],
    experience: [
      "4+ years of professional experience in structural design and construction",
      "Structural design for industrial platforms, pipe supports, sheds, and plant structures",
      "Multistoried hospital and institutional building projects",
      "Design of underground tanks, drainage, and infrastructure structures",
      "Bridge components including abutments, retaining walls, and protection works",
      "Design and detailing of industrial and infrastructure facilities across multiple sectors",
      "Handled government and private sector projects",
      "Coordinated with domestic and international clients",
    ],
    Achievements: [
      "Successfully delivered structural solutions across industrial, infrastructure, and building projects",
      "Expertise in handling complex retrofitting and strengthening projects",
      "Proven track record in multidisciplinary team coordination and project execution",
    ],
    softwareSkills: [
      "STAAD Pro",
      "ETABS",
      "SAFE",
      "SAP2000",
      "STRAP",
      "AutoCAD",
      "DraftSight",
      "MS Excel",
      "MS PowerPoint",
    ],
    education: [
      "B.Tech in Civil Engineering (Er. prefix)",
    ],
    ContactNumber: "",
    email: "",
  },
  {
    id: 11,
    name: "Nikhil Patra",
    role: "Senior AI Engineer",
    domain: "Artificial Intelligence, Data Engineering & Cloud Solutions",
    image: "/images/team/Nikhil Patra.jpg",
    summary:
      "Senior AI Engineer at SAP with extensive experience in Document AI and Data Engineering within SAP’s AI organization. Spearheading data initiatives and leading engineering teams to build scalable data pipelines, knowledge graphs, and cloud-based machine learning solutions. Experienced in AI-driven document processing, Retrieval-Augmented Generation (RAG), data lakes, and automation using AWS and SAP BTP. Strong background in full-stack development, research, and agile project management with expertise in delivering enterprise-grade AI solutions.",
    expertise: [
      "Document AI & Machine Learning Solutions",
      "Data Engineering & Automated Data Pipelines",
      "Knowledge Graphs & RAG Implementation",
      "Cloud Platforms (AWS, SAP BTP, AI Core)",
      "Full Stack Application Development",
      "Agile Methodologies, Scrum & TDD",
      "Project & Vendor Management",
      "Semantic Web & Data-Centric Systems",
    ],
    experience: [
      "11+ years of experience at SAP across AI development, data engineering, and software engineering roles",
      "Design and implementation of cloud-based ML document processing solutions",
      "Leadership of Data Engineering team managing annotation and data acquisition projects",
      "Development of knowledge graphs integrating heterogeneous data sources",
      "Experience in microservices-based payroll applications on HANA Cloud Platform",
      "Research experience in cyber defense, semantic data quality, and image processing",
      "Enterprise application development in HCM Recruiting and Payroll systems",
      "Experience working with banking, healthcare, and enterprise AI domains",
    ],
    Achievements: [
      "Led key AI data initiatives within SAP’s AI organization",
      "Built scalable data lakes and automated high-quality training data pipelines",
      "Successfully delivered AI-powered cloud solutions for enterprise applications",
      "Experience as Mindfulness Ambassador and Search Inside Yourself Trainer at SAP",
    ],
    softwareSkills: [
      "Python",
      "Java",
      "JavaScript",
      "C++",
      "AWS",
      "SAP BTP",
      "AI Core",
      "Metaflow",
      "UI5",
      "HANA Cloud Platform",
    ],
    education: [
      "M.Sc. in Computer Science – University of Bonn",
      "B.Tech in Computer Science and Engineering – Vellore Institute of Technology",
    ],
    ContactNumber: "",
    email: "",
  },
  {
    id: 12,
    name: "Dr. Aniket Bhalkikar",
    role: "Structural Engineering & Seismic Safety Specialist",
    domain: "Structural Engineering, Seismic Risk & Safety Assessment",
    image: "/images/team/Aniket Bhalkikar.jpg",
    summary:
      "Doctoral researcher and academic specializing in computer-aided structural design, rapid visual survey (RVS) methods, seismic safety assessment, and structural health monitoring (SHM) using experimental and machine learning tools.",
    expertise: [
      "Seismic Safety Assessment & Retrofitting",
      "Rapid Visual Survey (RVS) Methods",
      "Structural Health Monitoring (SHM)",
      "Earthquake Disaster Risk Indexing (EDRI)",
      "Soil-Structure Interaction Analysis",
      "Application of AI & ML in Structural Engineering",
    ],
    experience: [
      "Assistant Professor in Civil Engineering and Architecture at CHRIST University, Bengaluru (2022–Present)",
      "Research Assistant / Doctoral Researcher at EERC, IIIT Hyderabad (2014–2021) contributing to NDMA risk indexing projects",
      "Consultancy lead for South-Western Railway ROB health monitoring and structural retention projects",
      "Trainee Engineer at HCC Ltd. on underground cavern construction (2010)",
    ],
    Achievements: [
      "Developed NDMA's Earthquake Disaster Risk Indexing (EDRI) for 50 towns and 1 district",
      "Co-authored national primer on Rapid Visual Screening (RVS) for earthquake safety in India",
      "7+ peer-reviewed journal publications (Elsevier, Springer, Lecture Notes in Civil Engineering)",
      "8+ international conference publications (WCEE Chile/Japan/Italy, SEC, ICCMS)",
      "Ph.D. in Civil Engineering from IIIT Hyderabad (2022)",
    ],
    softwareSkills: [
      "SAP2000",
      "ETABS",
      "AutoCAD",
      "QGIS",
      "MATLAB",
      "Python",
      "Excel VBA & APIs",
    ],
    education: [
      "Ph.D. – Civil Engineering, IIIT Hyderabad (2014–2022, CGPA: 8.25)",
      "M.Tech – Computer Aided Structural Engineering, IIIT Hyderabad (2012–2014, CGPA: 8.11)",
      "B.E. – Civil Engineering, Marathwada Institute of Technology (2007–2011, 66.53%)",
    ],
    ContactNumber: "+91-9985004656",
    email: "aniketnnb@gmail.com",
  },
  {
    id: 13,
    name: "Er. Abhishek Samanta",
    role: "Civil Engineering & Infrastructure Solutions Contractor",
    domain: "Civil Construction & Infrastructure Projects",
    image: "/images/team/Abhishek Samanta.jpg",
    summary:
      "Registered 'A' Class PWD Civil Engineer Contractor with a proven track record of delivering structurally sound government infrastructure, road works, bridge canals, and major RCC structures across Odisha.",
    expertise: [
      "RCC Building & Commercial Construction",
      "Road Construction (RCC / WMM / GSB)",
      "Bridges & Canal Structural Works",
      "Minor Irrigation Infrastructure",
      "Government PWD Compliance & Operations",
      "Civil Site Supervision & Labor Management",
    ],
    experience: [
      "Proprietor and 'A' Class PWD Contractor managing and executing civic infrastructure projects across Odisha",
      "Contractor lead for minor irrigation structures, bridges, roads, and government residential complex construction",
      "Industrial contractor for RCC roads (Suguna Foods) and commercial campus works (MIT College)",
    ],
    Achievements: [
      "Successfully executed major Gunduraposi MIP Embankment Road for the Department of Water Resources, Odisha",
      "Constructed Drugs Inspector Office & Residence complex for PWD Dhenkanal Division",
      "Completed the 60-bed capacity Attendant Rest Shed at District Headquarters Hospital, Dhenkanal (2025)",
      "Constructed major bridge at RD 142/575 km on Gandia Branch Canal",
    ],
    softwareSkills: [
      "AutoCAD",
      "Project Estimation & Costing",
      "Site Management Tools",
      "Office Productivity Tools",
    ],
    education: [
      "Graduate in Civil Engineering (Er. prefix)",
    ],
    ContactNumber: "+91-9439730802",
    email: "abhisheksam91@gmail.com",
  },
  {
    id: 14,
    name: "Er. Sumit Pattanayak",
    role: "Associated Contractor – Civil & Infrastructure",
    domain: "Civil Engineering & PWD Infrastructure Projects",
    image: "/images/team/Sumit Pattanayak.jpg",
    summary:
      "Highly experienced Civil Engineer and Class ‘A’ Registered Government Contractor specializing in large-scale institutional, healthcare, residential, commercial, and structural infrastructure projects with over a decade of hands-on technical execution, cost control, and project administration.",
    expertise: [
      "RCC Framed Structure Execution",
      "Structural Detailing & Site Supervision",
      "Government Tender Works (PWD / EPC Mode)",
      "BOQ Preparation & Rate Analysis",
      "Healthcare & Hospital Infrastructure",
      "Educational & Institutional Buildings",
    ],
    experience: [
      "Associated Class ‘A’ Civil Contractor executing high-value public and private sector projects across Odisha",
      "Construction lead for 600-bed hospital project (Sason) and multiple 200-bed hospital blocks (Barbil, Angul)",
      "Commercial structure manager for G+3 IT building (Infocity) and Gram Vikas office complex",
    ],
    Achievements: [
      "Successfully registered as Class ‘A’ Civil Contractor with Engineer-in-Chief (Civil), Odisha",
      "Executed G+4, 600-Bed Hospital complex for Samaleswari Educational Trust, Sason, Sambalpur",
      "Constructed G+12 Residential Apartment project in Chandrasekharpur, Bhubaneswar",
      "Managed structural infrastructure for Sri Sri University academic blocks, Cuttack",
    ],
    softwareSkills: [
      "AutoCAD",
      "Project Cost Estimation & BOQ",
      "Site Execution Management",
      "Project Scheduling Tools",
    ],
    education: [
      "Graduate in Civil Engineering (Er. prefix)",
    ],
    ContactNumber: "",
    email: "",
  },
  {
    id: 15,
    name: "Dr. Ketan Kumar Nandi",
    role: "Fluvial Hydrodynamics & River Modeler Consultant",
    domain: "Water Resources, River Hydrodynamics & GIS",
    image: "/images/team/Ketan Kumar Nandi.jpg",
    summary:
      "Research scientist and academic with extensive experience in river hydrodynamics, river corridor management, underwater robotics application in water resources engineering, and advanced remote sensing cloud computing analyses (Google Earth Engine) for river basin management.",
    expertise: [
      "River Hydrodynamics & Corridor Management",
      "Fluvial Modeling (HEC-RAS, FLOW-3D, ANSYS)",
      "Remote Sensing & GIS (ArcGIS, QGIS, Google Earth Engine)",
      "Braided River Morphological Assessment",
      "Real-Time Dam Safety Monitoring Systems",
      "Underwater Robotics in Water Engineering",
    ],
    experience: [
      "Assistant Professor in Civil Engineering at SR University, Warangal (2025–Present)",
      "Post-Doctoral Fellow in Underwater Exploration Technologies at IIT Guwahati (2023–2025)",
      "Co-Principal Investigator in a ₹90 lakh dam safety monitoring project funded by TIH-IIT Guwahati",
      "River Modeler for cascading river interventions (NMHS) and Manas-Sankosh-Teesta-Ganga river linking project (NWDA)",
    ],
    Achievements: [
      "Awarded Best Presentation Award (HYDRO2020) by Indian Society of Hydraulics",
      "Published 9+ peer-reviewed journal papers (Journal of Hydrology, Advances in Water Resources, Ecohydrology)",
      "Participated in Jal Shakti Ministry's Brahmaputra Amantran Abhiyan national river expedition",
      "Completed Ph.D. in Civil Engineering (Water Resources) from IIT Guwahati (2023)",
    ],
    softwareSkills: [
      "FLOW-3D",
      "ANSYS",
      "HEC-RAS",
      "MATLAB",
      "C++",
      "ArcGIS",
      "QGIS",
      "Google Earth Engine",
    ],
    education: [
      "Ph.D. – Civil Engineering (Water Resources), IIT Guwahati (2018–2023)",
      "M.Tech – Civil Engineering (Water Resources), VSSUT Burla (2013–2015)",
      "B.Tech – Civil Engineering, Orissa Engineering College (2008–2012)",
    ],
    ContactNumber: "+91-8763077733",
    email: "ketannandi@gmail.com",
  },
  {
    id: 16,
    name: "Dr. Anindita Nath",
    role: "Remote Sensing & Geospatial Analyst Consultant",
    domain: "Remote Sensing, GIS & Coastal Hazards",
    image: "/images/team/Anindita Nath.jpg",
    summary:
      "Doctoral researcher and academic with over 8 years of research and teaching experience in Geo-Environmental Hazards (landslides, coastal erosion), climate change, and AI-enabled geospatial techniques.",
    expertise: [
      "Coastal Hazards & Shoreline Shifting (DSAS)",
      "Remote Sensing & GIS (ArcGIS, QGIS, GEE)",
      "Geo-AI & Land-Use Monitoring/Modeling",
      "Integrated Coastal Zone Management (ICZM)",
      "Environmental Vulnerability & Risk Mapping",
    ],
    experience: [
      "Former Researcher at Jadavpur University, Kolkata, specializing in coastal erosion and threats",
      "PhD Co-Supervisor collaborating with the University of Petroleum & Energy Studies (UPES), Dehradun",
      "Teaching Faculty in the Department of Geography at Bankim Sardar College, West Bengal (6+ years)",
    ],
    Achievements: [
      "Published 15+ peer-reviewed articles and 9 book chapters (Elsevier, Springer, Taylor & Francis)",
      "Editor of Springer book 'Assessment of Geo-Environmental hazards using AI enabled Geospatial Techniques'",
      "Active reviewer for reputed journals (Natural Hazards Research, GeoJournal, Spatial Information Research)",
      "Ph.D. in Science (Faculty of Interdisciplinary Studies, Law and Management), Jadavpur University",
    ],
    softwareSkills: [
      "ArcGIS",
      "QGIS",
      "ERDAS IMAGINE",
      "DSAS (Digital Shoreline Analysis System)",
      "Google Earth",
    ],
    education: [
      "Ph.D. – Science, Jadavpur University (2016–2021)",
      "P.G. Diploma – Applied Remote Sensing & GIS, Jadavpur University (2013–2015)",
      "M.Sc. – Geography & Environment Management, Vidyasagar University (2010–2012)",
      "B.Sc. – Geography (Honours), University of Calcutta (2007–2010)",
    ],
    ContactNumber: "+91-8013623429",
    email: "aninditan286@gmail.com",
  },
  {
    id: 17,
    name: "Dr. M. Uma Maheswar Rao",
    role: "GIS Analyst, SCRUM Master & Water Resources Specialist",
    domain: "GIS, Remote Sensing & Digital Twin Technology",
    image: "/images/team/M Uma Maheswar Rao.jpg",
    summary:
      "Doctoral researcher, academic, and Certified ScrumMaster (CSM) specializing in integrating GIS and Remote Sensing for environmental, urban, and hydrology engineering. Experienced in managing digital twins (Hyderabad 3D twin project) and academic engineering instruction.",
    expertise: [
      "GIS Analysis & Spatial Modeling (ArcGIS)",
      "Remote Sensing & Hydrology Engineering",
      "3D Digital Twin Modeling & Smart Cities",
      "Urban & Environmental Planning",
      "Agile Coordination & Scrum Framework",
    ],
    experience: [
      "GIS Analyst & SCRUM Master at IIT Hyderabad, working on the HMDA 3D Digital Twin project (2025–Present)",
      "Guest Faculty at NIT Hamirpur and PMEC Berhampur teaching civil engineering and GIS (2024–2025)",
      "Technical Consultant for GIZ GmbH supporting environmental and infrastructure projects (2022–2023)",
      "Researcher in Hydrology and Water Resources at NIT Rourkela (2019–2023)",
    ],
    Achievements: [
      "Earned Ph.D. in Hydrology and Water Resources Engineering from NIT Rourkela (2024)",
      "Certified ScrumMaster (CSM) for managing multidisciplinary technology and spatial teams",
      "Deployed spatial data models for the Hyderabad 3D Digital Twin project",
    ],
    softwareSkills: [
      "ArcGIS Desktop",
      "AutoCAD",
      "Microsoft Office",
      "Scrum/Agile Frameworks",
    ],
    education: [
      "Ph.D. – Hydrology and Water Resources Engineering, NIT Rourkela (2019–2024)",
      "M.Tech – Water Resources Engineering, VSSUT Burla (2015–2017)",
      "B.Tech – Civil Engineering, Centurion University (2011–2015)",
    ],
    ContactNumber: "",
    email: "",
  }
];

export const GROUPS = {
  coreTeam: [1, 3, 2, 8, 5],
  itAdvisors: [9, 11],
  remoteSensing: [15, 6, 16, 17],
  civilEngineering: [13, 14],
  structuralEngineering: [7, 10, 12],
  lawProfessionals: [4],
};

