import { Team, TeamMember} from "@/types/team"

export const TeamData: Team[] = [
  {
    id: 1,
    name: "Dr. Sovan Sankalp",
    role: "Partner & AI and Geospatial Applications Specialist",
    bio: "Leads AI-driven GIS and advanced hydrological intelligence.",
    image: "/images/team/Dr. Sovan Sankalp.jpeg",
  },
  {
    id: 2,
    name: "Dr. Asit Kumar Dandapat",
    role: "Partner & Hydrology and GIS Specialist",
    bio: "Expert in GIS-based hydrology and climate impact modelling.",
    image: "/images/team/Dr. Asit Kumar Dandapat.jpeg",
  },
  {
    id: 3,
    name: "Dr. Arpan Pradhan",
    role: "Partner & Fluvial Hydraulics Specialist",
    bio: "Specialist in river hydraulics and flood modelling systems.",
    image: "/images/team/Dr. Arpan Pradhan.jpeg",
  },
  {
    id: 4,
    name: "Aloka Prasad Mishra",
    role: "Legal, HR and Compliance Specialist",
    bio: "Handles legal compliance, labor relations, and governance.",
    image: "/images/team/Aloka Prasad Mishra.jpg",
  },
  {
    id: 5,
    name: "Chiranjeeb Kumar Sahoo",
    role: "Urban Planner",
    bio: "Works on IoT systems and full-stack software development.",
    image: "/images/team/Chiranjeeb Kumar Sahoo.jpeg",
  }
];

export const Team_Member: TeamMember[] = [
  {
  id: 1,
  name: "Dr. Sovan Sankalp",
  role: "Water Resources Engineer",
  domain: "Hydrology, GIS & AI/ML",
  image: "/images/team/Dr. Sovan Sankalp.jpeg",
  summary:
    "Experienced water resources engineer, researcher, and academic specializing in hydrological analysis, groundwater systems, urban flood modelling, and geospatial intelligence, with strong integration of GIS, remote sensing, and AI/ML techniques.",
  expertise: [
    "Hydrological Analysis & Modelling",
    "Groundwater Hydrology & Assessment",
    "Urban Flood Analysis & Risk Mapping",
    "Remote Sensing & GIS Applications",
    "AI/ML-based Time Series Forecasting",
    "Spatial & Temporal Drought Monitoring",
    "Urban Climate & Impervious Surface Analysis",
  ],
  experience: [
    "10+ years of research, teaching, and project experience in Water Resources Engineering",
    "Urban flood susceptibility mapping and MCDM-based risk analysis",
    "Groundwater variability and hydro-climatic extreme assessment",
    "Government- and policy-oriented research on climate resilience and sustainability",
    "Organizer and resource person for international conferences, FDPs, GIS Day events, and workshops",
  ],
  Achievements: [
    "20+ SCI/Scopus/ESCI indexed journal publications",
    "Published book chapters with Elsevier on AI/ML applications in hydrology and climate analysis",
    "Developed deep learning–based drought, soil moisture, and groundwater forecasting frameworks",
    "Reviewer for SCI & Scopus indexed journals",
    "Published three patents in geospatial intelligence, agriculture ICT, and thermal regulation systems",
  ],
  softwareSkills: [
    "HEC-RAS",
    "HEC-HMS",
    "CCHE-2D",
    "CES",
    "ArcGIS Pro",
    "ENVI",
    "ERDAS IMAGINE",
    "Google Earth Engine",
    "Python (Jupyter Notebook)",
    "R",
    "MATLAB",
    "SPSS",
    "AutoCAD",
  ],
  education: [
    "Ph.D. – Civil Engineering (Water Resources Engineering), NIT Rourkela",
    "M.Tech – Civil Engineering (Water Resources Engineering), NIT Rourkela",
    "B.Tech – Civil Engineering, SOA University, Odisha",
  ],
  ContactNumber: new Int16Array([9, 1, 7, 0, 0, 8, 0, 3, 8, 8, 3, 3]),
  email: "sankalpsovan9@gmail.com",
},
{
  id: 2,
  name: "Asit Kumar Dandapat",
  role: "Research Scientist",
  domain: "Hydrology & Civil Engineering",
  image: "/images/team/Dr. Asit Kumar Dandapat.jpeg",
  summary:
    "Research Scientist with 3+ years of experience in hydrology, groundwater modelling, GIS–RS, and climate impact assessment, with strong contributions to drought and flood modelling, soil erosion analysis, and sustainable water management studies.",
  expertise: [
    "Hydrology & Groundwater Modelling",
    "GIS & Remote Sensing Applications",
    "Drought & Flood Susceptibility Analysis",
    "Soil Erosion & RUSLE Modelling",
    "Climate Change Impact Assessment",
    "MCDA-based Decision Support Systems",
  ],
  experience: [
    "Research Scientist at ICAR-IIWM, working on GIS-based hydrology, groundwater modelling, and climate-resilient agriculture studies",
    "Field investigations and decision-support map generation for drought and flood assessments",
    "Civil Engineer involved in site execution, quality control, and supervision of infrastructure projects",
    "Assistant Professor teaching Civil Engineering subjects and guiding academic projects",
    "Watershed development and natural resource management under government programmes",
  ],
  Achievements: [
    "10+ SCI/Scopus indexed research publications",
    "GATE qualified in 2019, 2021, 2023, 2024, and 2025",
    "Best Poster Award – ESRI Conference 2025",
    "Best Poster Award – ICAR-IIWM Climate-Smart Agriculture 2024",
    "Recognized for GIS-based climate-smart agriculture and SDG-focused modelling studies",
  ],
  softwareSkills: [
    "ArcGIS Pro",
    "QGIS",
    "Google Earth Engine",
    "R Studio",
    "Python",
    "MODFLOW (GMS/WMS)",
    "ERDAS Imagine",
    "SNAP",
    "OriginPro",
    "MS Office",
  ],
  education: [
    "Ph.D. – Civil Engineering (Water Resources), CUTM (2021–2025)",
    "M.Tech – Water Resources Engineering, NIT Rourkela (87.30%)",
    "B.Tech – Civil Engineering, BPUT",
  ],
  ContactNumber: new Int16Array([9, 1, 8, 6, 5, 8, 0, 0, 3, 7, 1, 7]),
  email: "asit80t@gmail.com",
},
{
  id: 3,
  name: "Dr. Arpan Pradhan",
  role: "Water Resources Engineer",
  domain: "Fluvial Hydraulics & River Engineering",
  image: "/images/team/Dr. Arpan Pradhan.jpeg",
  summary:
    "Experienced civil engineer and academic specializing in fluvial hydraulics, river engineering, and urban flood management, integrating experimental studies, numerical modelling, and geospatial analysis for sustainable water resources solutions.",
  expertise: [
    "Fluvial & Open Channel Hydraulics",
    "River Modelling & Stream Gauging",
    "Urban Flooding & Drainage Analysis",
    "Experimental & Numerical Hydraulics",
    "Remote Sensing & GIS Applications",
    "Sustainable Water Resources Engineering",
  ],
  experience: [
    "10+ years of research and teaching experience in Water Resources Engineering",
    "PhD research on stage–discharge modelling of meandering compound channels",
    "Field expertise in river hydraulics and stream gauging trained by IAHR–WMO–IAHS (France)",
    "Contributor to government- and industry-oriented research on flood risk and hydraulic sustainability",
    "Organizer and resource person for FDPs, conferences, and national workshops",
  ],
  Achievements: [
    "15+ SCI/Scopus indexed journal publications",
    "Design Patent granted (2024) for Manual Washing Machine",
    "Patent on disease vulnerability and combat mapping using geospatial techniques",
    "Patent on sustainable bricks using iron-ore tailings and waste foundry sand",
    "Active professional memberships in ASCE, IAHR, IAHS, IEI, and ISRS",
  ],
  softwareSkills: [
    "HEC-RAS",
    "MIKE FLOOD",
    "MIKE BASIN",
    "ANSYS Fluent",
    "OpenFOAM",
    "ArcGIS",
    "QGIS",
    "MATLAB",
    "SPSS",
    "GeneXPro",
    "AutoCAD",
    "LaTeX",
  ],
  education: [
    "Ph.D. – Civil Engineering, National Institute of Technology Rourkela",
    "M.Tech – Water Resources Engineering, National Institute of Technology Rourkela",
    "B.Tech – Civil Engineering, Biju Patnaik University of Technology, Odisha",
  ],
  ContactNumber: new Int16Array([9, 1, 9, 4, 3, 9, 2, 9, 1, 9, 0, 0]),
  email: "arpan.pradhan@christuniversity.in",
},
{
  id: 4,
  name: "Aloka Prasad Mishra",
  role: "Law Professional",
  domain: "Legal Affairs, HR & Institutional Governance",
  image: "/images/team/Aloka Prasad Mishra.jpg",
  summary:
    "Qualified law professional with strong academic grounding in law and management, specializing in labor and industrial relations, institutional compliance, HR governance, and industry–academia coordination, supporting ethical decision-making and organizational effectiveness.",
  expertise: [
    "Labor Laws & Industrial Relations",
    "Employment Compliance & Advisory",
    "Legal Documentation & Case Interpretation",
    "Dispute Resolution & Advisory Support",
    "Institutional Governance & Compliance",
    "Industry–Academia Coordination",
  ],
  experience: [
    "Advisory support in labor and industrial relations matters",
    "Institutional compliance and governance support",
    "Training, mentoring, and academic administration roles",
    "Stakeholder coordination between academia and industry",
    "Legal documentation, regulatory reporting, and policy support",
  ],
  Achievements: [
    "Recognized for ethical decision-making and governance-oriented advisory",
    "Active contributor to institutional compliance and HR policy frameworks",
    "Mentoring-driven leadership in academic and administrative environments",
  ],
  softwareSkills: [
    "MS Office",
    "Documentation & Compliance Systems",
    "HR Information Systems (HRIS)",
    "Legal Research & Case Management Tools",
  ],
  education: [
    "Bachelor of Laws (LLB) – Labor & Industrial Relations, Madhusudan Law University",
    "MBA – HR & Finance",
  ],
  ContactNumber: new Int16Array([]),
  email: "",
}
];
